import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { getRecipes } from "@/lib/content";
export const metadata: Metadata = { title: "Ricette", description: "Ricette semplici e stagionali, con ingredienti quotidiani.", alternates: { canonical: "/ricette" } };

export default async function RecipesPage({ searchParams }: { searchParams: Promise<{ q?: string; categoria?: string }> }) {
  const [{ q, categoria }, recipes] = await Promise.all([searchParams, getRecipes()]);
  const search = q?.trim().toLocaleLowerCase("it-IT");
  const categories = [...new Set(recipes.map((recipe) => recipe.category))];
  const filtered = recipes.filter((recipe) => (!search || `${recipe.title} ${recipe.description} ${recipe.category}`.toLocaleLowerCase("it-IT").includes(search)) && (!categoria || recipe.category === categoria));
  return <div className="page-shell"><section className="page-intro page-gutter"><span className="eyebrow">Idee per la tua tavola</span><h1>Ricette di ogni<br /><em>giorno, con cura.</em></h1><p>Preparazioni semplici, ingredienti familiari e spazio per adattare ogni idea ai tuoi gusti.</p></section><section className="listing-section page-gutter"><form className="listing-filters" action="/ricette"><label className="search-field"><span className="sr-only">Cerca una ricetta</span><input type="search" name="q" placeholder="Cerca una ricetta…" defaultValue={q} /></label><label className="filter-field"><span className="sr-only">Filtra per categoria</span><select name="categoria" defaultValue={categoria ?? ""}><option value="">Tutte le categorie</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><button className="filter-button" type="submit">Cerca <span aria-hidden="true">→</span></button></form>{filtered.length ? <div className="recipe-grid">{filtered.map((recipe, index) => <Link className="recipe-card" href={`/ricette/${recipe.slug}`} key={recipe.slug}><div className="recipe-card-image"><Image loading={index === 0 ? "eager" : "lazy"} unoptimized={recipe.image.startsWith("/api/media/") || /^https?:\/\//i.test(recipe.image)} src={recipe.image} alt={recipe.imageAlt} fill sizes="(max-width: 760px) 100vw, 33vw" className="cover-image" /></div><div className="editorial-meta"><span>{recipe.category}</span><span>{recipe.prepMinutes} minuti · {recipe.difficulty}</span></div><h2>{recipe.title}</h2><p>{recipe.description}</p><span className="card-link">Apri la ricetta <span aria-hidden="true">→</span></span></Link>)}</div> : <div className="listing-empty"><strong>Nessuna ricetta trovata.</strong><span>Prova a modificare la ricerca o la categoria.</span></div>}</section><section className="small-disclaimer page-gutter"><span className="eyebrow">Da ricordare</span><p>Le ricette sono spunti generali: quantità e indicazioni possono variare in base alle esigenze personali.</p></section></div>;
}
